export const APP_SETTINGS = {
    FLOORS_COUNT: 7,
    ELEVATOR_CAPACITY: 2,
    ELEVATOR_SPEED_PER_FLOOR_MS: 1000,
    LOADING_TIME: 800,
    PASSENGER_SPAWN_INTERVAL: {
        MIN: 4000,
        MAX: 10000,
    },
    MAX_PEOPLE_IN_QUEUE: 5,
    BACKGROUND_COLOR: '#FFF'
};
