import {ELEVATOR_CONFIG} from "./elevator.config";
import {BUILDING_CONFIG} from "./building.config";

export const PASSENGER_SETTINGS = {
    PASSENGER_WIDTH: 20,
    PASSENGER_HEIGHT: 30,
    PASSENGER_RADIUS: 4,
    BORDER_WIDTH: 2,
    COLOR_UP: 0x0000FF,
    COLOR_DOWN: 0x00FF00,
    BACKGROUND_COLOR: 0xFFFFFF,
    ALPHA_FILL: 0,
    LABEL_FONT_SIZE: 14,
    LABEL_COLOR: 0x000000,
    LABEL_OFFSET_X: 10,
    LABEL_OFFSET_Y: 15,
    PASSENGER_START_X: BUILDING_CONFIG.WIDTH - 50,
    PASSENGER_Y_OFFSET: 30,

    QUEUE: {
        START_X: ELEVATOR_CONFIG.WIDTH + 10,
        SPACING: 10,
    },

    PASSENGER_QUEUE_MOVE_TIME: 400,
    PASSENGER_MOVE_TIME: 600,
    PASSENGER_EXIT_TIME: 800,
};
